<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.htmlunit</groupId>
    <artifactId>htmlunit-websocket-client-parent</artifactId>
    <version>4.11.0</version>

    <name>HtmlUnit WebSocket Client Parent</name>
    <packaging>pom</packaging>
    <description>
        The HtmlUnit Websocket Client Parent
    </description>
    <url>https://www.htmlunit.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.build.timestamp.format>yyyy-MM-dd HH:mm</maven.build.timestamp.format>
        <additionalparam>-Xdoclint:none</additionalparam>
    </properties>


    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/HtmlUnit/htmlunit/issues/</url>
    </issueManagement>
    <inceptionYear>2021</inceptionYear>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:https://github.com/HtmlUnit/htmlunit</connection>
        <developerConnection>scm:git:https://github.com/HtmlUnit/htmlunit</developerConnection>
        <url>https://github.com/HtmlUnit/htmlunit</url>
    </scm>

    <ciManagement>
        <system>Jenkins</system>
        <url>https://jenkins.wetator.org/view/HtmlUnit/</url>
    </ciManagement>

    <developers>
        <developer>
            <name>Ronald Brill</name>
            <id>rbri</id>
            <email>rbri@rbri.de</email>
            <url>http://www.wetator.org/</url>
            <timezone>+1</timezone>
        </developer>
    </developers>

    <distributionManagement>
        <snapshotRepository>
            <id>s01-sonatype-nexus-snapshots</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>s01-sonatype-nexus-staging</id>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2</url>
        </repository>
    </distributionManagement>

    <repositories>
        <repository>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
            <id>OSS Sonatype snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <modules>
        <module>jetty9</module>
        <module>native</module>
    </modules>

</project>
